# Generated by Django 2.2.3 on 2019-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190716_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name_plural': 'All Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='YouAndM3', max_length=255),
        ),
    ]
